#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted
# at the root of a domain.
# `domain` is used to generate absolute URLs.
# (required to generate a valid feed)
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com
base_url: /
domain: ian.mccowan.space


#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: Ian McCowan
# A description of your site to be used in header meta tags.
description:
# Used in the site feed.
email: imccowan@gmail.com
# Your site's subtitle.
subtitle:
# Your site's title. (required to generate a valid feed)
title: small clever rooms


#
# THIRD PARTY SETTINGS
#

# If you'd like to enable Google Analytics for your site, set this to your tracking code.
analytics:

# Color code blocks
pygmentize: True

# Containers
containers:
    essays:
        url: /study/essays/<slug>/
    music:
        url: /study/music/<slug>/

#
# Chances are you probably don't need to touch anything below here.
#

archive_layout: archive.html
archives_url: /livingroom/
tag_layout: tag.html
tags_url: /livingroom/tags/
